#!/usr/bin/env python3
"""Compare two dataselect binaries for identical behavior.

Every run of the option matrix is executed with both binaries and the written
miniSEED, the record summary, the log output and the exit status must match.
Intended as the gate for changes that are meant to be purely internal.

    test/compare-ab.py ./dataselect.ref ./dataselect

Input is taken from ../libmseed/test/data plus overlapping data generated by
make-baddata.py.  Working files are written to test/compare-tmp/, which is
removed when everything matches and left in place when something does not.
"""

import argparse
import filecmp
import itertools
import os
import shutil
import subprocess
import sys

TESTDIR = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(TESTDIR, os.pardir, "libmseed", "test", "data")
TMP = os.path.join(TESTDIR, "compare-tmp")
MAKEBADDATA = os.path.join(TESTDIR, "make-baddata.py")

# Option dimensions, combined as a cross product
PRUNE = [[], ["-Pr"], ["-Ps"], ["-Pe"]]
WINDOW = [[], ["-ts", "2012-05-12T00:00:03.0", "-te", "2012-05-12T00:00:10.0"]]
QUALITY = [[], ["-Q", "R"]]
TOLERANCE = [[], ["-tt", "0"], ["-tt", "0.5"], ["-rt", "0.1"]]
BESTVERSION = [[], ["-bv", "0"], ["-bv", "2"]]


def inputs():
    """Return the list of (name, [input files]) to run the matrix against."""
    v2 = os.path.join(DATA, "reference-testdata-steim2.mseed2")
    v3 = os.path.join(DATA, "reference-testdata-steim2.mseed3")
    nsec = os.path.join(DATA, "reference-testdata-nsec.mseed3")

    cases = [
        ("v2", [v2]),
        ("v3", [v3]),
        ("nsec", [nsec]),
        # The same file twice, the existing suite's way of forcing overlap
        ("duplicate", [v2, v2]),
        ("mixed", [v2, v3]),
    ]

    for shape in ("clean", "scattered", "dense"):
        path = os.path.join(TMP, "%s.mseed" % shape)
        subprocess.run([sys.executable, MAKEBADDATA, shape, "-r", "60", "-c", "3",
                        "-o", path], check=True, stdout=subprocess.DEVNULL)
        cases.append((shape, [path]))

    # Overlapping publication versions, to exercise 'best' prioritization
    versions = os.path.join(TMP, "versions.mseed")
    with open(versions, "wb") as out:
        for quality in (b"R", b"D", b"Q"):
            with open(os.path.join(DATA, "reference-testdata-steim2.mseed2"), "rb") as fp:
                data = bytearray(fp.read())

            for offset in range(0, len(data), 512):
                data[offset + 6] = quality[0]

            out.write(data)

    cases.append(("versions", [versions]))

    return cases


def selectionfile():
    """Write and return a selection file covering the generated sources."""
    path = os.path.join(TMP, "selection.txt")

    with open(path, "w") as out:
        out.write("XX_TEST_*_B_H_Z 2012-05-12T00:00:02 2012-05-12T00:00:11\n")
        out.write("XX_T0*_*_B_H_? 2012-05-12T00:00:04 2012-05-12T00:00:30\n")
        out.write("XX_*_*_*_*_* * *\n")

    return path


def run(binary, args, tag):
    """Run one binary, returning (returncode, stdout, stderr, output bytes)."""
    outfile = os.path.join(TMP, "out-%s.mseed" % tag)
    summary = os.path.join(TMP, "sum-%s.txt" % tag)

    proc = subprocess.run(
        [binary, "-o", outfile, "-out", summary] + args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    return (proc.returncode, proc.stdout, proc.stderr, outfile, summary)


def compare(ref, new, args, index, verbose):
    """Run both binaries with 'args' and report any difference."""
    refresult = run(ref, args, "ref")
    newresult = run(new, args, "new")

    problems = []

    if refresult[0] != newresult[0]:
        problems.append("exit status %d != %d" % (refresult[0], newresult[0]))

    # The binary names appear in usage and error text, compare only when equal
    if refresult[1] != newresult[1]:
        problems.append("stdout differs")

    if refresult[2] != newresult[2]:
        problems.append("stderr differs")

    for label, refpath, newpath in (("output", refresult[3], newresult[3]),
                                    ("summary", refresult[4], newresult[4])):
        refexists = os.path.exists(refpath)
        newexists = os.path.exists(newpath)

        if refexists != newexists:
            problems.append("%s existence differs" % label)
        elif refexists and not filecmp.cmp(refpath, newpath, shallow=False):
            problems.append("%s bytes differ" % label)

    if problems:
        print("FAIL [%d] %s" % (index, " ".join(args)))
        for problem in problems:
            print("       %s" % problem)

        if refresult[2] != newresult[2]:
            print("     --- ref stderr ---")
            print(refresult[2].decode(errors="replace")[:2000])
            print("     --- new stderr ---")
            print(newresult[2].decode(errors="replace")[:2000])

        return False

    if verbose:
        print("ok   [%d] %s" % (index, " ".join(args)))

    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("reference", help="known good dataselect binary")
    parser.add_argument("candidate", help="dataselect binary under test")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="report every case, not only failures")
    parser.add_argument("-L", "--loglevel", default="-v",
                        help="verbosity passed to dataselect (default: -v)")
    args = parser.parse_args()

    for binary in (args.reference, args.candidate):
        if not os.path.isfile(binary):
            sys.exit("%s: not found" % binary)

    if os.path.exists(TMP):
        shutil.rmtree(TMP)
    os.makedirs(TMP)

    selection = selectionfile()
    cases = inputs()

    combinations = list(itertools.product(PRUNE, WINDOW, QUALITY, TOLERANCE, BESTVERSION))
    failures = 0
    total = 0

    for name, files in cases:
        for prune, window, quality, tolerance, bestversion in combinations:
            for selectopt in ([], ["-s", selection]):
                # A selection file and an explicit window are alternatives
                if selectopt and window:
                    continue

                options = ([args.loglevel] + prune + window + selectopt +
                           quality + tolerance + bestversion + files)

                total += 1
                if not compare(args.reference, args.candidate, options, total,
                               args.verbose):
                    failures += 1

        print("  %-10s %d cases, %d failures" % (name, total, failures))

    print("\n%d cases, %d failures" % (total, failures))

    if failures == 0:
        shutil.rmtree(TMP)
        return 0

    print("Working files left in %s" % TMP)
    return 1


if __name__ == "__main__":
    sys.exit(main())
