.TH DATASELECT 1 2024/5/28
.SH NAME
miniSEED data selection, sorting and pruning

.SH SYNOPSIS
.nf
dataselect [options] file1 [file2 file3 ...]
.fi

.SH DESCRIPTION
\fBdataselect\fP selects, sorts and prunes miniSEED data.  Any output
data will always be sorted by ascending time-series segments.  Various
data selection operations are possible including time criteria, the
removal of duplicate data and the splicing of partially overlapping
data records to form continuous time-series.

Data pruning, removal of overlap, can be performed at either the
record or sample level.  Pruning at the record level guarantees that
records are never unpacked/repacked, but this could potentially leave
small amounts of overlap in the data.  Pruning at the sample level
will remove any overlap and splice data to within the time-series
tolerance, this requires the unpacking and repacking of data records
and is done in a modification-minimizing way.

When removing overlapping data records or samples the concept of
priority is used to determine from which time-series data should be
removed if overlaps are detected.  By default the priority is given to
the highest publication version (or v2 quality data).  When the
qualities are the same priority is given to the longer segment.

Multiple input files will be read in the order specified and processed
all together as if all the data records were from the same file.  The
program must read input data from files; input from pipes, etc. is not
possible.

Files on the command line prefixed with a '@' character are input list
files and are expected to contain a simple list of input files, see
\fBINPUT LIST FILE\fP for more details.

Each input file may be specified with an explict byte range to read.
The program will begin reading at the specified start offset and stop
reading at the specified end range.  See \fBINPUT FILE RANGE\fP for
more details.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-H         "
Print verbose program usage including details of archive format
specification and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-tt \fIsecs\fP"
Specify a time tolerance for constructing continous trace
segments. The tolerance is specified in seconds.  The default
tolerance is 1/2 of the sample period.

.IP "-rt \fIdiff\fP"
Specify a sample rate tolerance for constructing continous trace
segments. The tolerance is specified as the difference between two
sampling rates.  The default tolerance is tested as: (abs(1-sr1/sr2) <
0.0001).

.IP "-snd"
Skip non-miniSEED records.  By default the program will stop when
it encounters data that cannot be identified as a miniSEED record.
This option can be useful with full SEED volumes or files with bad
data.

.IP "-E\fP"
Consider all publication versions (or v2 qualities) equal when
determining priority for pruning.  By default priority is given to
the data with the highest publication version.

.IP "-s \fIselectfile\fP"
Limit processing to miniSEED records that match a selection in the
specified file.  The selection file contains parameters to match the
SourceID (network, station, location, channel), publication version
(or v2 quality), and time range for input records.
As a special case, specifying "-" will result in selection
lines being read from stdin.  For more details see the \fBSELECTION
FILE\fP section below.

.IP "-ts \fItime\fP"
Limit processing to miniSEED records that start after or contain
\fItime\fP.  The preferred format of the \fItime\fP argument
is: 'YYYY-MM-DD[THH:MM:SS.FFFFFFFFF]'.

.IP "-te \fItime\fP"
Limit processing to miniSEED records that end before or contain
\fItime\fP.  The perferred format of the \fItime\fP argument
is: 'YYYY-MM-DD[THH:MM:SS.FFFFFFFFF]'.

.IP "-m \fImatch\fP"
Limit input to records that match this globbing pattern, the
\fImatch\fP is tested against the full FDSN Source ID:
'FDSN:NET_STA_LOC_B_S_SS'.

.IP "-o \fIfile\fP"
Write all output data to output \fIfile\fP instead of replacing the
original files.  If '-' is specified as the output file all output
data will be written to standard out.  By default the output file
will be overwritten, changing the option to \fI+o file\fP appends to
the output file.

.IP "-A \fIformat\fP"
All output records will be written to a directory/file layout defined
by \fIformat\fP.  All directories implied in the \fIformat\fP string
will be created if necessary.  The option may be used multiple times
to write input records to multiple archives.  See the \fBARCHIVE
FORMAT\fP section below for more details including pre-defined archive
layouts.

.IP "-CHAN \fIdirectory\fP"
.IP "-CHAN \fVCHANLAYOUT\fP"
.IP "-QCHAN \fIdirectory\fP"
.IP "-CDAY \fIdirectory\fP"
.IP "-SDAY \fIdirectory\fP"
.IP "-BUD \fIdirectory\fP"
.IP "-SDS \fIdirectory\fP"
.IP "-CSS \fIdirectory\fP"
Pre-defined output archive formats, see the \fBARCHIVE FORMAT\fP
section below for more details.

.IP "-Pr         "
Prune, remove overlap data, at the record level.  This will result in
removal of all the completely overlapped data records.  Small,
partial-record overlaps might remain in the data.

.IP "-Ps         "
Prune, remove overlap data, at the sample level.  This will result in
removal of all the completely overlapped data samples.  When data
records partially overlap the lowest priority record is unpacked,
trimmed and repacked.  Record trimming requires a supported data
encoding, if unsupported (primarily older encodings) the record will
be in the output untrimmed.

.IP "-Pe         "
Prune (trim) returned traces to user specified edges (start and end
times) at the sample level. This option will not remove overlap data
within specified start and end time window.  Caveats the same as for
\fB-Ps\fP.

.IP "-Q pubversion"
Change the data publication version or quality indicator for all output
records to the specified value.  If this value is one of the letters:
R, D, Q or M it will be translated to the appropriate publication of
1, 2, 3, 4 respectively.  If the value is not one of these letters it
must be a number between 1 and 255.  Note that miniSEED v2 data quality
indicators only support values 1-4, and all higher values will result in
a publication version of 4 (aka data quality 'M').

.IP "-out file    "
Print a summary of output records to the specified file.  Any existing
file will be appended to.  Specify the file as '-' to print to stdout
or '--' to print to stderr.  Each summary line contains FDSN Source ID,
publication version, start time, end time, byte count, and
sample count for each output trace segment.

.IP "-outprefix prefix"
Include the specified prefix string at the beginning of each line of
summary output when using the \fI-out\fP option.  This is useful to
identify the summary output in a stream that is potentially mixed with
other output.

.SH THE PRUNING PROCESS

The pruning algorithm used is independant of the file structure and
organization.  Data from all input files are parsed and a map created
for every data record and their relationship in continuous time
series segments.

Each data record time coverage in each continuous time-series is
compared to the time coverage of every other continous time-series.
When overlap is detected, data is optionally removed from the lower
priority time-series until the overlap is minimized or completely
removed depending on the pruning option specified.

.SH "SELECTION FILE"
A selection file is used to match input data records based on network,
station, location and channel information.  Optionally a quality and
time range may also be specified for more refined selection.  The
non-time fields may use the '*' wildcard to match multiple characters
and the '?' wildcard to match single characters.  Character sets may
also be used, for example '[ENZ]' will match either E, N or Z.
The '#' character indicates the remaining portion of the line will be
ignored.

Example selection file entires (the first four fields are required)
.nf
#SourceID                  Starttime              Endtime             Pubversion
FDSN:IU_ANMO_*_B_H_?
FDSN:II                    *                      *                   3
FDSN:IU_COLA_00_L_H_[ENZ]  *                      *                   1
FDSN:IU_COLA_00_L_H_Z      2008-4-9T10:00:00Z    2008-4-9T10:30:00Z
.fi

\fBWarning:\fP with a selection file it is possible to specify
multiple, arbitrary selections.  Some combinations of these selects
are not possible.  See \fBCAVEATS AND LIMITATIONS\fP for more details.

.SH "INPUT LIST FILE"
A list file can be used to specify input files, one file per line.
The initial '@' character indicating a list file is not considered
part of the file name.  As an example, if the following command line
option was used:

.nf
\fB@files.list\fP
.fi

The 'files.list' file might look like this:

.nf
data/day1.mseed
data/day2.mseed
data/day3.mseed
.fi

.SH "INPUT FILE RANGE"
Each input file may be specified with an associated byte range to
read.  The program will begin reading at the specified start offset
and finish reading when at or beyond the end offset.  The range is
specified by appending an '@' charater to the filename with the start
and end offsets separated by a dash:

.nf
filename.mseed@[startoffset][-][endoffset]
.fi

For example: "filename.mseed@4096-8192".  Both the start and end
offsets are optional.  The dash separator is optional if no end
offset is specified.

.SH "ARCHIVE FORMAT"
The pre-defined archive layouts are as follows:

.nf
-CHAN dir   :: dir/%n.%s.%l.%c
-VCHAN dir  :: dir/%n.%s.%l.%c.%v
-QCHAN dir  :: dir/%n.%s.%l.%c.%q
-CDAY dir   :: dir/%n.%s.%l.%c.%Y:%j:#H:#M:#S
-SDAY dir   :: dir/%n.%s.%Y:%j
-BUD dir    :: dir/%n/%s/%s.%n.%l.%c.%Y.%j
-SDS dir    :: dir/%Y/%n/%s/%c.D/%n.%s.%l.%c.D.%Y.%j
-CSS dir    :: dir/%Y/%j/%s.%c.%Y:%j:#H:#M:#S
.fi

An archive format is expanded for each record using the following
substitution flags:

.nf
  \fBn\fP : network code, white space removed
  \fBs\fP : station code, white space removed
  \fBl\fP : location code, white space removed
  \fBc\fP : channel code, white space removed
  \fBY\fP : year, 4 digits
  \fBy\fP : year, 2 digits zero padded
  \fBj\fP : day of year, 3 digits zero padded
  \fBH\fP : hour, 2 digits zero padded
  \fBM\fP : minute, 2 digits zero padded
  \fBS\fP : second, 2 digits zero padded
  \fBF\fP : fractional seconds, 4 digits zero padded
  \fBv\fP : publication version, 1-255
  \fBq\fP : data quality if possible, otherwise pub version (D, R, Q, M, or #)
  \fBL\fP : data record length in bytes
  \fBr\fP : sample rate (Hz) as a rounded integer
  \fBR\fP : sample rate (Hz) as a float with 6 digit precision
  \fB%\fP : the percent (%) character
  \fB#\fP : the number (#) character
.fi

The flags are prefaced with either the \fB%\fP or \fB#\fP modifier.
The \fB%\fP modifier indicates a defining flag while the \fB#\fP
indicates a non-defining flag.  All records with the same set of
defining flags will be written to the same file.  Non-defining flags
will be expanded using the values in the first record for the
resulting file name.

Time flags are based on the start time of the given record.

.SH ARCHIVE FORMAT EXAMPLES

The format string for the predefined \fIBUD\fP layout:

\fB/archive/%n/%s/%s.%n.%l.%c.%Y.%j\fP

would expand to day length files named something like:

\fB/archive/NL/HGN/HGN.NL..BHE.2003.055\fP

As an example of using non-defining flags the format string for the
predefined \fICSS\fP layout:

\fB/data/%Y/%j/%s.%c.%Y:%j:#H:#M:#S\fP

would expand to:

\fB/data/2003/055/HGN.BHE.2003:055:14:17:54\fP

resulting in day length files because the hour, minute and second are
specified with the non-defining modifier.  The hour, minute and second
fields are from the first record in the file.

.SH LEAP SECOND LIST FILE
NOTE: A list of leap seconds is included in the program and no external
list should be needed unless a leap second is added after year 2023.

If the environment variable LIBMSEED_LEAPSECOND_FILE is set it is
expected to indicate a file containing a list of leap seconds in NTP
leap second list format. Some locations where this file can be obtained
are indicated in RFC 8633 section 3.7:
https://www.rfc-editor.org/rfc/rfc8633.html#section-3.7

If present, the leap seconds listed in this file will be used to
adjust the time coverage for records that contain a leap second.
Also, leap second indicators in the miniSEED headers will be ignored.

.SH ERROR HANDLING AND RETURN CODES
Any significant error message will be pre-pended with "ERROR" which
can be parsed to determine run-time errors.  Additionally the program
will return an exit code of 0 on successful operation and 1 when any
errors were encountered.

.SH CAVEATS AND LIMITATIONS

With the ability to specify multiple, arbitrary data selections it is
possbile to specify very complex and pathological compound selections.
When pruning samples from records into order to fit the requested
selections, this program is limited to trimming samples from the
beginning and/or end of the record.  This means it is not possible to
select two or more non-intersecting time ranges from a single record.
Put another way, one cannot select select data from the beginning and
end, but not the middle of a record.  The work-around for this
limitation is to run the program once for each selection.

.SH AUTHOR
.nf
Chad Trabant
EarthScope Data Services
.fi
